@Library(value="kids-first/aws-infra-jenkins-shared-libraries@feature/add-tests", changelog=false) _
ecs_service_type_1_standard {
    projectName = "kf-api-persona"
    environments = "dev,qa,prd"
    docker_image_type = "alpine"
    deploy_scripts_version = "feature/add-tests"
    ecs_service_type_1_version = "feature/add-tests"
    internal_app = "false"
    entrypoint_command = "yarn start" 
    quick_deploy = "true"
    external_config_repo = "false"
    container_port = "3232"
    vcpu_container             = "2048"
    memory_container           = "4096"
    vcpu_task                  = "2048"
    memory_task                = "4096"
    health_check_path = "/status"
    create_default_iam_role = "0"
    dependencies = "ecr"
    additional_ssl_cert_domain_name = "*.kidsfirstdrc.org"
    friendly_dns_name = "persona"
}
