@Library(value="kids-first/aws-infra-jenkins-shared-libraries", changelog=false) _
ecs_service_type_1_standard {
    projectName = "kf-api-persona"
    environments = "dev,qa,prd"
    create_default_iam_role = "0"
    docker_image_type = "alpine"
    internal_app = "false"
    entrypoint_command = "npm start"
    deploy_scripts_version = "master"
    quick_deploy = "true"
    external_config_repo = "false"
    container_port = "3232"
    vcpu_container             = "2048"
    memory_container           = "4096"
    vcpu_task                  = "2048"
    memory_task                = "4096"
    health_check_path = "/status"
    dependencies = "ecr"
    additional_ssl_cert_domain_name = "*.kidsfirstdrc.org"
    friendly_dns_name = "persona"
    create_additional_internal_alb = "1"
    publish_to_public_repo = "true"
}
