export const createProfile = (fields = {}) => ({
  _id: "",
  title: "",
  firstName: "",
  lastName: "",
  egoId: "",
  roles: [],
  acceptedTerms: true,
  email: "",
  institutionalEmail: "",
  eraCommonsID: "",
  department: "",
  story: "",
  bio: "",
  jobTitle: "",
  institution: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  country: "",
  zip: "",
  phone: "",
  website: "",
  googleScholarId: "",
  twitter: "",
  facebook: "",
  github: "",
  linkedin: "",
  orchid: "",
  interests: [],
  acceptedKfOptIn: false,
  acceptedNihOptIn: false,
  acceptedDatasetSubscriptionKfOptIn: false,
  isPublic: false,
  isActive: false,
  sets: [],
  hashedEmail: "",
  ...fields,
});

export const buildUserCollection = (...profiles) => [...profiles].flat()